# title: localized, see _data
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Consulting website for jplejeune
# baseurl: "/consultant-website" # The subpath for your project
# url: "https://jplej.github.io" # Your GitHub Pages user site URL
twitter_username: jekyllrb
github_username:  jekyll
permalink: pretty
collections:
  service_blocks:
    output: false
  landing_blocks:
    output: false 
  # posts:
   # permalink: /blog/:slug/

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-polyglot
  - jekyll-seo-tag
  - jekyll-tailwindcss
#  - jekyll-postcss

postcss:
  cache: false


languages: ["en", "fr"]
default_lang: "en"
exclude_from_localization: [assets, command.sh]
parallel_localization: true

sass:
  sourcemap: never

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache/
  - .jekyll-cache/
  - command.sh
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
