title: Services
items:
- title: Évaluation Initiale
  description: Évaluation complète avec ateliers, interviews et analyse pour fournir un rapport et une feuille de route améliorant l'efficacité et la prise de décision du front office.
- title: Ingénierie des Données
  description: Création et maintenance de lacs de données conformes et évolutifs, avec intégration de l'IA et surveillance proactive.
- title: Intelligence d'Affaires
  description: Développement de plateformes et tableaux de bord pour des insights en temps réel, des workflows automatisés et une prise de décision optimisée.
