title: Services
items:
- title: Évaluation Initiale
  description: Évaluation complète comprenant des ateliers, des entretiens et des analyses, pour fournir un rapport et une feuille de route visant à améliorer l'efficacité du front office et la prise de décision.
  icon: "fa fa-paper-plane"
- title: Ingénierie des Données
  description: Création et maintenance de lacs de données et bases de données conformes et évolutives, avec intégration de l'intelligence artificielle et surveillance proactive.
  icon: "fa fa-database"
- title: Intelligence d'Affaires
  description: Développement de plateformes de données et de tableaux de bord pour offrir une vue en temps réel, automatiser les flux de travail et optimiser la prise de décision.
  icon: "fa fa-bar-chart"
