title: Services
items:
  - title: Évaluation Initiale
    description: "Évaluation approfondie comprenant des ateliers, des entretiens et des analyses pour fournir un rapport, une vision et une feuille de route stratégique."
    icon: "fa fa-paper-plane"
  - title: Ingénierie des Données
    description: "Création et gestion de lacs de données et de bases de données conformes et évolutives, avec intégration de l'intelligence artificielle et surveillance proactive."
    icon: "fa fa-database"
  - title: Intelligence d'Affaires
    description: "Développement de plateformes de données et de tableaux de bord pour des analyses en temps réel, des flux de travail automatisés et une prise de décision optimisée."
    icon: "fa fa-bar-chart"
