name: 'Automatic build'

on:
  push:
    branches:
      - main
    paths-ignore:
      - .gitignore
      - _site

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Install Ruby and Bundler 2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.0' # Specify an exact Ruby version from the available list

      - name: Install Bundler 2
        run: |
          gem install bundler:2.3.0 
          bundle install

      - name: Build & Deploy to GitHub Pages
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_ACTOR: ${{ github.actor }}
          JEKYLL_ENV: production
        uses: BryanSchuetz/jekyll-deploy-gh-pages@master
