name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Ruby for Jekyll
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'  # Adjust to match your Ruby version

      # Step 3: Install Jekyll and Bundler
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      # Step 4: Build the Jekyll site
      - name: Build Jekyll site
        run: bundle exec jekyll build

      # Step 5: Deploy to the 'publish' branch
      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout --orphan publish
          git rm -rf .
          cp -r _site/* .
          git add .
          git commit -m "Deploy site to 'publish' branch"
          git push --force origin publish
